name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Sass
        run: npm install -g sass

      - name: Build CSS
        run: sass ./scss/main.scss ./dist/style.css --no-source-map --style=compressed

      - name: Copy files to dist
        run: |
          mkdir -p dist
          cp index.html dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
